CREATE CONSTRAINT TRIGGER trg_enforce_consolidation_material_lot AFTER INSERT OR UPDATE OF consolidation_group_id, finishing_send_id ON public.outbound_sends DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION enforce_consolidation_material_lot();
CREATE TRIGGER aircraft_touch_updated BEFORE UPDATE ON public.aircraft FOR EACH ROW EXECUTE FUNCTION kstc_touch_updated_at();
CREATE TRIGGER kit_books_touch_updated BEFORE UPDATE ON public.kit_books FOR EACH ROW EXECUTE FUNCTION kstc_touch_updated_at();
CREATE TRIGGER kit_components_touch_updated BEFORE UPDATE ON public.kit_components FOR EACH ROW EXECUTE FUNCTION kstc_touch_updated_at();
CREATE TRIGGER kit_installations_touch_updated BEFORE UPDATE ON public.kit_installations FOR EACH ROW EXECUTE FUNCTION kstc_touch_updated_at();
CREATE TRIGGER kit_lots_touch_updated BEFORE UPDATE ON public.kit_lots FOR EACH ROW EXECUTE FUNCTION kstc_touch_updated_at();
CREATE TRIGGER kit_parties_touch_updated BEFORE UPDATE ON public.kit_parties FOR EACH ROW EXECUTE FUNCTION kstc_touch_updated_at();
CREATE TRIGGER kit_sales_touch_updated BEFORE UPDATE ON public.kit_sales FOR EACH ROW EXECUTE FUNCTION kstc_touch_updated_at();
CREATE TRIGGER kit_skus_touch_updated BEFORE UPDATE ON public.kit_skus FOR EACH ROW EXECUTE FUNCTION kstc_touch_updated_at();
CREATE TRIGGER klcl_touch BEFORE UPDATE ON public.kit_lot_component_lots FOR EACH ROW EXECUTE FUNCTION kstc_touch_updated_at();
CREATE TRIGGER stc_certificates_touch_updated BEFORE UPDATE ON public.stc_certificates FOR EACH ROW EXECUTE FUNCTION kstc_touch_updated_at();
CREATE TRIGGER stc_issuances_guard BEFORE DELETE OR UPDATE ON public.stc_issuances FOR EACH ROW EXECUTE FUNCTION kstc_issuance_guard();
CREATE TRIGGER stc_requests_touch_updated BEFORE UPDATE ON public.stc_requests FOR EACH ROW EXECUTE FUNCTION kstc_touch_updated_at();
CREATE TRIGGER stock_requests_follow_wo_trg AFTER UPDATE OF status ON public.work_orders FOR EACH ROW EXECUTE FUNCTION stock_requests_follow_wo();
CREATE TRIGGER stock_requests_touch_trg BEFORE UPDATE ON public.stock_requests FOR EACH ROW EXECUTE FUNCTION stock_requests_touch();
CREATE TRIGGER trg_alloc_aiud AFTER INSERT OR DELETE OR UPDATE ON public.customer_order_allocations FOR EACH ROW EXECUTE FUNCTION trg_alloc_recalc();
CREATE TRIGGER trg_cert_packages_immutable BEFORE DELETE OR UPDATE ON public.cert_packages FOR EACH ROW EXECUTE FUNCTION cert_packages_block_mutation();
CREATE TRIGGER trg_cleanup_material_loads AFTER DELETE ON public.job_materials FOR EACH ROW EXECUTE FUNCTION cleanup_material_loads_on_jm_delete();
CREATE TRIGGER trg_co_line_default_due BEFORE INSERT ON public.customer_order_lines FOR EACH ROW EXECUTE FUNCTION default_co_line_due_date();
CREATE TRIGGER trg_co_lines_uat BEFORE UPDATE ON public.customer_order_lines FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_co_uat BEFORE UPDATE ON public.customer_orders FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_customers_uat BEFORE UPDATE ON public.customers FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_enforce_machine_bar_length BEFORE INSERT OR UPDATE OF bar_length, job_id ON public.job_materials FOR EACH ROW EXECUTE FUNCTION enforce_machine_bar_length();
CREATE TRIGGER trg_fulfill_co_on_tco BEFORE UPDATE ON public.jobs FOR EACH ROW WHEN ((((new.status)::text = 'pending_tco'::text) AND ((old.status)::text IS DISTINCT FROM 'pending_tco'::text) AND (new.co_fulfillment_applied_at IS NULL))) EXECUTE FUNCTION fulfill_co_on_tco_entry();
CREATE TRIGGER trg_line_au AFTER UPDATE OF status, quantity_fulfilled ON public.customer_order_lines FOR EACH ROW EXECUTE FUNCTION trg_line_recalc_parent();
CREATE TRIGGER trg_material_usage_reconciliation AFTER INSERT ON public.material_usage FOR EACH ROW EXECUTE FUNCTION raise_material_reconciliation_flags();
CREATE TRIGGER trg_parts_length_family_fill BEFORE INSERT OR UPDATE OF part_number, description, length_family_key ON public.parts FOR EACH ROW EXECUTE FUNCTION parts_length_family_fill();
CREATE TRIGGER trg_set_schedule_qty_basis BEFORE INSERT OR UPDATE ON public.jobs FOR EACH ROW EXECUTE FUNCTION set_schedule_qty_basis();
CREATE TRIGGER trg_truncate_schedule_seconds BEFORE INSERT OR UPDATE OF scheduled_start, scheduled_end ON public.jobs FOR EACH ROW EXECUTE FUNCTION trg_truncate_schedule_seconds();
CREATE TRIGGER update_downtime_logs_updated_at BEFORE UPDATE ON public.machine_downtime_logs FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_job_documents_timestamp BEFORE UPDATE ON public.job_documents FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_jobs_timestamp BEFORE UPDATE ON public.jobs FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_locations_timestamp BEFORE UPDATE ON public.locations FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_machines_timestamp BEFORE UPDATE ON public.machines FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_part_machine_durations_updated_at BEFORE UPDATE ON public.part_machine_durations FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_parts_timestamp BEFORE UPDATE ON public.parts FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_profiles_timestamp BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_tool_instances_updated_at BEFORE UPDATE ON public.tool_instances FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_tools_updated_at BEFORE UPDATE ON public.tools FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_work_orders_timestamp BEFORE UPDATE ON public.work_orders FOR EACH ROW EXECUTE FUNCTION update_updated_at();
